[package]
name = "impulse"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "impulse"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
fs_extra = "1.3.0"
lazy_static = "1.5.0"
